### PR TITLE
Add  10.0.19041.1806 dlls support

### PR DESCRIPTION
**Pull request by Max-RM**

### CODE REVIEW

**Comment by Max-RM** [comment]
IMG_20220731_220447
IMG_20220731_220436

**Comment by Max-RM** [comment]
Change folder name  10.0.19041.1806 to  19041.1806, because 10.0.19041.1806 don't work for users

**Comment by QwertyTheCoder** [comment]
Actually this would be a good idea to pull this off

**Comment by Max-RM** [comment]
> Actually this would be a good idea to pull this off

it looks like the repository owner just disappeared, but users can just use my repository instead of this

**Comment by QwertyTheCoder** [comment]
@Max-RM Thanks, i request you to view this https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked

**Comment by Max-RM** [comment]
> Thanks, i request you to view this https://github.com/QwertyTheCoder/Minecraft-bedrock-cracked
Ik that exist many cloned repo

**Review by QwertyTheCoder — APPROVED** [review]

**Comment by QwertyTheCoder** [comment]
@Max-RM I think tinedpakgamer wont merge this pull request until we our dead, lol.

**Comment by Max-RM** [comment]
> @Max-RM I think tinedpakgamer wont merge this pull request until we our dead, lol.

then use my repository as the main one

**Comment by QwertyTheCoder** [comment]
> Author



> > @Max-RM I think tinedpakgamer wont merge this pull request until we our dead, lol.
> 
> then use my repository as the main one



> > @Max-RM I think tinedpakgamer wont merge this pull request until we our dead, lol.
> 
> then use my repository as the main one

hmm.

**Review by QwertyTheCoder — APPROVED** [review]

**Pull request merged**
